<template>
  <div class="loadingio-spinner-eclipse-dnymn4sgsj8"><div class="ldio-2hwih29r73o">
    <div></div>
  </div></div>
</template>

<style scoped>
@keyframes ldio-2hwih29r73o {
  0% { transform: rotate(0deg) }
  50% { transform: rotate(180deg) }
  100% { transform: rotate(360deg) }
}
.ldio-2hwih29r73o div {
  position: absolute;
  animation: ldio-2hwih29r73o 1s linear infinite;
  width: 160px;
  height: 160px;
  top: 20px;
  left: 20px;
  border-radius: 50%;
  box-shadow: 0 4px 0 0 #e15b64;
  transform-origin: 80px 82px;
}
.loadingio-spinner-eclipse-dnymn4sgsj8 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
.ldio-2hwih29r73o {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-2hwih29r73o div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>